;This file, which is a part of the Underwater Runins Diamon Escape, 
;contains all of the tables that are kept in the program memory. 
;These tables include the characters that appear on the screen 
;and the words for the screen setup.
;It is best to include this file first in order to prevent excessive 
;"Relative branch out of reach" scenarios.


;===================== MULTIPLE CHARACTERS ADDRESS  ==============================
JmpTable:
.dw Char_0<<1
.dw Char_1<<1; 
.dw Char_2<<1
.dw Char_3<<1
.dw Char_4<<1
.dw Char_5<<1
.dw Char_6<<1
.dw Char_7<<1
.dw Char_8<<1
.dw Char_9<<1
.dw Char_A<<1  
.dw Char_B<<1
.dw Char_C<<1 
.dw Char_D<<1
.dw Char_E<<1 
.dw Char_F<<1 
.dw Char_H<<1  
.dw Char_R<<1 
.dw Char_I<<1 
.dw Char_T<<1 
.dw Char_S<<1 
.dw Char_U<<1 
.dw Char_N<<1 
.dw Char_O<<1 
.dw Char_dot<<1 
.dw Char_Space<<1  
.dw Char_Y<<1 
.dw Char_Q<<1  